### PR TITLE
Fix bone attachment translation difference

### LINKED ISSUE #102: Bone Attachment not working correctly
Example project

[leg_t04_ik.blend.zip]()

### PR DESCRIPTION
**Pull request by Jason0214**
Fix #102, godot and blender has bone attachment relative to different bone joint, so there are a difference of bone length in y-axis translation.

TODO:  Fix the translation in animation frames

### CODE REVIEW

**Comment by Jason0214** [comment]
@Marc The bone attachment issue is fixed

**Comment by Jason0214** [comment]
@Zylann the bone attachment should be fixed now

**Comment by Zylann** [comment]
Ok I'll try this exporter when I have time, but what about the DAE import that initially was the one not working? Is this written down somewhere?

**Comment by Jason0214** [comment]
I don't think DAE could be used to export your scene, your scene has some object parented to bones, as far as I know DAE doesn't support that (correct me I am wrong

**Pull request merged**
