### PR TITLE
[NO MERGE] [WIP] support blender 2.8

### PR DESCRIPTION
**Pull request by Jason0214**
Related to #122 

- implemented some basic features:  (now mesh is exportable . lol)
    - register addon
    - naive handle of collections and view_layers
    - corrected some broken mesh API

It still need much time until it fully complete because there so many API breaking change in blender2.8,  however I will open the PR just to draw attention...

Aside from API name change, there are some new components or patterns which may need to be thoroughly think through.

1. [collections and view_layers](https://code.blender.org/2017/09/view-layers-and-collections/), it is more powerful than previous version, so more can be exported
2. [depsgraph](https://en.blender.org/index.php/Dev:2.8/Source/Depsgraph) which is kind of a runtime cache of objects, every object update need to go through `depsgraph`
3. material, internal material is gone, so more user may export cycle/eevee material, material part need to be elaborated more.

I am glad blender 2.8 has [python API doc](https://docs.blender.org/api/blender2.8/) available, which makes things much easier

### CODE REVIEW

**Comment by Jason0214** [comment]
@akien-mga what do you think of managing such a breaking change, should we have a separate branch for blender 2.8 or keep it in the same code base?    

I am thinking it would be very messy to checking the version number everywhere 2.7 and 2.8 differs, as there are so many,  so even if keeping it in the same code base, the cleaner way would be create two directory, one for 2.7 and other for 2.8.

**Comment by akien-mga** [comment]
I think separate branches for 2.79 (e.g. `blender-2.79`) and 2.80 (`master`) would likely be good. The main development would thus focus on 2.80, and some duplication of work would be needed if we want to keep adding features to the `blender-2.79` branch.

Using two folders in the `master` branch would also work, but it would also imply such duplication of work and in a more binding way (if we have both versions in `master`, users would expect the same level of support for both).

Alternatively, we could try to make a compatibility library and put the 2.7 and 2.8 specific code there, but it doesn't seem trivial seen the current changes you had to do. Maybe the Blender community will provide such a library, but if not, the way forward will eventually be to drop 2.79 development/freeze it at the current stage (+ occasional important bug fixes if there's contributors willing to backport them).

**Comment by Jason0214** [comment]
Primitive support for blender2.8 is up on [branch2.8](https://github.com/godotengine/godot-blender-exporter/tree/blender2.8),  most functionality should be fine except material which need time to have a thorough check. 

@akien-mga  Sorry, for the late response. Thank you very much! I will later switch the master branch to blender2.8.

**Comment by Jason0214** [comment]
@akien-mga by the way, do you know any github configurations to add some protection on branch?  I kind of afraid I did some thing wrong by accident production branch existed..

**Comment by akien-mga** [comment]
I can add protection rules to branches yes, what kind of protection do you want for which branches?
screenshot_20181217_083059

**Comment by Jason0214** [comment]
Could add a `restrict who can push to matching branches`,  disable my direct push to these two branches. Thanks!

**Comment by akien-mga** [comment]
I think it might restrict your ability to merge PRs, so I'm not sure it would be a good idea. If you're afraid of pushing to the `godotengine` repo by mistake, you can change your `origin` remote to point to your own fork, and make `godotengine` the `upstream` remote. This way `git push` would attempt to push branches to your own fork, not the main repo.

**Comment by akien-mga** [comment]
I added force-push protection rules on the master and blender2.8 branches though. If you ever need to force push an update to either for some reason, ping me :)

**Comment by Jason0214** [comment]
Ah, sounds good, thanks again!

**Pull request closed without merging**
