### PR TITLE
Generate scene diff as artifacts for failed regressions

### PR DESCRIPTION
**Pull request by Jason0214**

### CODE REVIEW

**Comment by Calinou** [comment]
chunk.io is now said to be invite-only. You'll need to specify a token in the Travis CI secrets if this is merged.

**Comment by Jason0214** [comment]
Thanks for the notes!

**Comment by Calinou** [comment]
Another service you could use for this is [0x0.st](https://0x0.st), but its terms of use forbid using it for CI build artifacts. Is the payload you're uploading considered a CI build artifact?

**Comment by Jason0214** [comment]
@Calinou I found I can get the patch by just parsing the Travis log, so there is no need to use any third-party storage.
Thank you very much for the suggestion.

**Comment by rcorre** [comment]
It seems that if you have a version mismatch, travis fails before generating a diff: https://travis-ci.org/github/godotengine/godot-blender-exporter/jobs/748124341#L916

**Comment by Jason0214** [comment]
@rcorre ah, right. This can not be handled. Mix Blender2.8 and 2.9 scenes would not work in any case.

**Comment by Jason0214** [comment]
Merge this change as it wouldn't affect the functionality of the CI and possibly could do some good.

**Pull request merged**
