### PR TITLE
Fix Docker Build Upgrading Python to 3.6

### LINKED ISSUE #395: Docker build fails on setuptools upgrade
**OS:**
Ubuntu Linux 18.04.2

**Godot version:**
3.2.3 (Not relevant since this issue only relates to running the `docker build` command)

**Blender version:**
From `Dockerfile` (2.81 as of this writing on `master`)

**Docker version:**
20.10.4

**Issue description:**
The build step described in the `README.md`:

```shell
sudo docker build . -t godot_blender_exporter:latest
```

...fails with the following output:

```
Step 6/13 : RUN pip3 install --upgrade setuptools
 ---> Running in a71db98cd95c
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Minimal reproduction project:**
Simply checkout `master` and run the `docker build` command listed in the `README.md`.

### PR DESCRIPTION
**Pull request by timjklein36**
The Docker build for testing via a container was not working due to an issue with Python 3.5 on the Ubuntu Xenial base image. This fixes #395 by upgrading the version of Python in the resulting image to version 3.6.

With this version upgrade the way to run `pylint` has been updated in `test_entrypoint.sh` to simply use the `pylint` command.

Additionally, the later version of Docker did not work with the example commands provided in the `README.md` so those were also updated.

This fix was tested with Docker version 20 on Ubuntu and Arch Linux.

### CODE REVIEW

**Comment by Calinou** [comment]
Out of curiosity, why not upgrade the base image to `18.04` or even `20.04` instead?

**Comment by timjklein36** [comment]
@Calinou That approach makes sense to me. I just wasn't sure who/what uses this workflow and wanted to impact the existing setup in as few ways as possible.

**Comment by Calinou** [comment]
I think it'd be better to upgrade the base image, but I'll let @rcorre or another maintainer decide on this.

**Comment by rcorre** [comment]
I'm not a maintainer, just a regular contributor :)

Still, I'd agree with @Calinou that it makes more sense to update the base image. I only picked `xenial` for the Dockerfile to be consistent with [travis](https://github.com/godotengine/godot-blender-exporter/blob/master/.travis.yml#L1), but it might be time to update the CI too.

**Comment by Jason0214** [comment]
Agree we better update both the CI and docker to `bionic`. The CI was setup three years ago and is falling behind.

@rcorre Do you have other thoughts on this change?  May be we can merge it for now and I will find some time to bump the base image and update the reference scene.

**Comment by rcorre** [comment]
Yup, this is fine for now

**Pull request merged**
