### PR TITLE
Ignore empty nodes that have hide_render set.

### LINKED ISSUE #211: Empty exported with hide_render
**OS:**

Linux

**Godot version:**

```
3.1.beta9.official
```

**Blender version:**

```
Blender 2.79 (sub 7)
	build hash: a29446da526d
```

**Issue description:**

1. Open a new scene in blender
2. Add a new `Mesh/Cube`. Toggle `hide_render`.
3. Add a new `Empty/PlainAxes`. Toggle `hide_render`.
4. Export to godot
5. The .escn contains the empty

I expected the empty to be ignored during export, just like the mesh was.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/3155088/example.zip)

### PR DESCRIPTION
**Pull request by rcorre**
Cameras/Lamps/Meshes are ignored in the export if hide_render is set.
The same should be true of Empty objects.

Fixes #211.

### CODE REVIEW

**Comment by Jason0214** [comment]
Thanks!  However, I have some consideration, if the empty object has a non-trivial transform, ignoring it would cause changes on its children (if has) objects' transform. 

And btw does the empty object ignored if you uncheck the `EMPTY` in `Object Types` of exporting configuration?

**Comment by rcorre** [comment]
> If the empty object has a non-trivial transform, ignoring it would cause changes on its children (if has) objects' transform

Yes, but this is true of parent objects in general, and not a reason to disable this behavior specifically for Empties. Following the "rule of least surprise", I think empties should have the same behavior as other objects in this regard.

FWIW, I was surprised that setting `hide_render` on a parent didn't just skip exporting the entire sub-hierarchy, but there might be valid reasons for that.

> And btw does the empty object ignored if you uncheck the EMPTY in Object Types of exporting configuration?

Yes, but this ignores _all_ Empties. I want to ignore some empties and export others.

I have two use cases here:

1. I want to have BoneAttachments at a character's hands, but there should be nothing in them by default. Parenting an object to the bone and setting `hide_render` achieves this. (I can use a Mesh for this, but Empty seems like the most obvious choice for a placeholder).

2. I have linked a group from one blender file into another. It is used only as a reference when animating, so I don't want it exported. When you link a group, blender automatically creates an empty as the parent. In this case, I don't have the choice of using another type.

**Comment by rcorre** [comment]
For reference, here is a scene where one cone is parented to an Empty, and another is parented to a Mesh. Both parents are translated, rotated, and set to `hide_render`. When exported (with my patch), both lose their parent transform component. So the behavior with Empty is consistent with other objects.

**Comment by Jason0214** [comment]
> FWIW, I was surprised that setting hide_render on a parent didn't just skip exporting the entire sub-hierarchy, but there might be valid reasons for that.

I think it's because `hide_render` has the scope of object, not the subtree. i.e. `hide_render` on parent does not affect its children's visibility in rendering.

---

The use cases explain the necessity very well, I will merge it. Thanks again!

**Pull request merged**
