### PR TITLE
Implement some Geometry node shader outputs.

### PR DESCRIPTION
**Pull request by rcorre**
Implements a subset of the geometry shader node outputs that trivially
map to godot shader inputs.

See #280.

I added a test file that sets color based on the X position of the vertices:

### CODE REVIEW

**Comment by Jason0214** [comment]
Thanks for your work!
The `Position` in geometry works good, however, for `Normal` and `Tangent` you may need to use `self.view_to_world(..., is_direction=True)` to do the conversion. The space conversion handling of point and direction is different.

You can use this setup to check it gives the same behaviour in Godot and Blender,
Screen Shot 2019-12-08 at 18 09 51

And it would be better if it still throw warnings for not supported sockets, like `Incoment`,  `Parametric`

**Comment by rcorre** [comment]
Thanks for the review! Using `is_direction=True` gives a matching result for `Normal`, but not `Tangent`. I've never used `Tangent` before, so I'm actually not sure what is expected here.




The further cube on top is using `Normal` with the cycles setup you referenced earlier, the closer cube is the same setup but using `Tangent` instead.

**Comment by rcorre** [comment]
Actually that is maybe just blender and godot interpreting tangent differently for a flat surface, I guess the tangent could really be in any direction along that surface (assuming "tangent" in this context means any vector perpendicular to the normal).

**Comment by rcorre** [comment]
Ok, I just replaced the cube with a sphere in the example to have something with less room for interpretation :)

**Comment by Jason0214** [comment]
If `TANGENT` is not working trivially, probably you can just leave it unsupported. I will check it myself later. 

The other changes are very good and I will merge it. Thank you for your work!

**Comment by rcorre** [comment]
Hi @Jason0214, just wanted to check if there is any update on merging. I believe `TANGENT` is working properly, but my initial cube example was ambiguous (godot and blender had different but both valid interpretations of the tangent on a flat surface). I replaced it with a sphere, which renders the same in both.

**Comment by Jason0214** [comment]
It looks good, I will merge it.

**Pull request merged**
