### PR TITLE
fix tangent handedness

### LINKED ISSUE #118: Normal map and tangent exporting checkup
This is a checkup ensuring this exporter still export `tangent` and `normal map` after https://github.com/godotengine/godot/pull/23760 merged.

( I am a little lost in godot's tangent space, different handness stuff.. so I just build scene and visually checking the correctness,  both d3d normal map (i.e. negative green) and openGl normal map (i.e. positive green) are tested, I hope it is sufficient

**blender version**: *2.79a*
**godot version**: both *3.0.6* and *custom build 3.1* (build with [fix_tangent_direction branch](https://github.com/BastiaanOlij/godot/tree/fix_tangent_direction))
**platform**: macOS *10.13*
**godot-blender-exporter version**: current head [a7c022](https://github.com/godotengine/godot-blender-exporter/commit/a7c0022374b6a78fe05c905d0430b0a66d7cdc25)
**testing project**:  [tangent_checkup.zip](https://github.com/godotengine/godot-blender-exporter/files/2603284/mesh_tangent_checkup.zip)

----
### Tangent
I created simple meshes (cube, plane and sphere), uv unwrap them, and then export to escn file. **Normal map textures are applied inside godot**, so it is checking for correctness of tangent value.

open escn in Godot 3.0:
screen shot 2018-11-20 at 20 27 43

open escn in Godot 3.1
screen shot 2018-11-20 at 20 42 26

<del>Using both DX and GL example normal map texture seems rendering to correct result. </del>
*actually the shadow position is not right*

----
#### Cycle Material
Also I tested exporting normal map in cycle material. Here I create meshes (cube, plane and sphere), uv unwrap them, **assign a normal map only cycle material to mesh in blender**, then export to escn file.

The scene in blender looks like:
screen shot 2018-11-20 at 21 50 58

open escn in Godot 3.0
screen shot 2018-11-20 at 22 03 21

open escn in Godot 3.1
screen shot 2018-11-20 at 22 26 48

<del>As the exporter should export the scene as it is in blender, I think it is also correct.</del>
*actually the shadow position is not right*

-----

**Bugs**:
1. Tangent not right, cross product of tangent and binormal should be inverted

2. exporting the normal map in cycle material to escn generated a very low resolution normal map when zoomed in, the issue is texture are not detected as `normal map` by godot, so missing some conversion steps
screen shot 2018-11-20 at 23 40 28

### PR DESCRIPTION
**Pull request by Jason0214**
fix #118

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
I had looked at this briefly a little while ago so sorry for the late reaction, I was fairly sick last week and only just started catching up on things now.

There was a discussion on twitter on the right orientation for normal maps and how they now are reversed. Based on the original PR I based my changes on and rechecking my work baking maps from blender I agree with those findings and I'm working on changing the way Godot handles bi-tangents so this flip is no longer needed.

So hold off on merging this PR until I can confirm my findings and submit the changes to Godot. It may no longer be needed :)

**Comment by Jason0214** [comment]
Sorry to hear that you are sick, hope you are recovered now.  
The tangent direction stuff is not very straightforward to think through ( at least for me ), anyway really appreciate your work and keep me updated 😊

**Comment by BastiaanOlij** [comment]
I think you can cancel this Jason, I haven't had time to fully test it but my latest changes were merged and it should mean there is no need to invert the bi-tangents. Your current master should give the right results.

**Comment by Jason0214** [comment]
Sure, I will close it.  Really appreciate your work!

**Pull request closed without merging**
