### PR TITLE
Fix export crash on RGB and Value const node

### LINKED ISSUE #241: release 2.8 issues
I hope you guys know, but just in case - physics and material export do not work for release version of blender-2.80. Looks like either data structures changed or it was not working from start (with 2.8). Enabling material or physics produce exporter crashes.

### PR DESCRIPTION
**Pull request by Jason0214**
1. Fix crash on RGB and Value const node by adding a new identifier, fix #241 
2. Add support for limited blend type of MixRGB shader node, including
blend type (MIX, ADD, SUB, MUL, DIV, DIFF, DARKEN, LIGHTEN)

### CODE REVIEW

**Comment by slapin** [comment]
Thank you so much for the fix!

While at this, what is exportable way to set up different UV scale for different textures when composing material of nodes? Is there any?

**Comment by Jason0214** [comment]
@slapin 

In the current stage, the answer is there isn't any. I only made the material node exporter to use the active UV. You can create an issue if you like and I think I am able to make it support 2UV channels.

**Comment by slapin** [comment]
That is not about UV channels per se I guess, it is about multiplying
UV to some value (as shader is exported anyway I think this should be
no problem to add).
Example is scaling tiling texture to better match surface. But I need
it to be implemented independently for each texture.
In Godot shader language that would be ALBEDO = texture(u1, UV
*vec2(a, b)) * texture(u2, UV * vec2(c, d)).rgb;
and Blender node in question would be mapping or vector math.

**Comment by Jason0214** [comment]
Sorry, I am not much a material guy, so correct me if I am wrong.  You are asking what is best way to scale an UV and use it for texture?   yeah, I think you can make use of the mapping node with scale (You need to find out whether use Texture mode or Point mode, they behave different), and certainly I think vector math node also satisfies your use case.

**Pull request merged**
